mysite/authapp/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import LogoutRedirect, get_cookies, set_cookies, \
    get_session, set_session, RegisterView, AboutMeView, UserUpdateView, UsersListView, UserDetailsView

app_name = 'authapp'

urlpatterns = [
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('about-me/<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('users-list/', UsersListView.as_view(), name='users-list'),
    path('users-details/<int:pk>/', UserDetailsView.as_view(), name='users-details'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='authapp/login.html',
                                     redirect_authenticated_user=True,), name='login'),
    path('logout/', LogoutRedirect.as_view(), name='logout'),
    path('set-cookies/', set_cookies, name='set-cookies'),
    path('get-cookies/', get_cookies, name='get-cookies'),
    path('set-session/', set_session, name='set-session'),
    path('get-session/', get_session, name='get-session'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from .sitemaps import sitemaps

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls'), name='shop'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

urlpatterns += [
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('request/', include('requestdataapp.urls'), name='request'),
    path('accounts/', include('authapp.urls'), name='auth'),
    path('blogs/', include('blogapp.urls'), name='blogs'),
    path('shop/', include('shopapp.urls'), name='shop'),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

mysite/authapp/models.py
from django.contrib.auth.models import User
from django.db import models


def avatar_path(instance: 'Profile', filename: str) -> str:
    '''
    Генерирует путь до аватара в профиле
    :param instance: Объект профиля
    :param filename: название файла
    :return: Путь до аватара
    '''

    return "avatar/{}/{}".format(instance.user.pk, filename)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True, null=True)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_path)

mysite/authapp/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, TemplateView, UpdateView, ListView, DetailView

from authapp.models import Profile


class AboutMeView(TemplateView):
    template_name = 'authapp/about_me.html'


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'authapp/register.html'
    success_url = reverse_lazy('authapp:about-me')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)

        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)

        return response

class LogoutRedirect(LogoutView):
    next_page = reverse_lazy('authapp:login')


class UserUpdateView(UserPassesTestMixin, UpdateView):
    model = Profile
    fields = 'avatar',
    template_name = 'authapp/profile_update.html'

    def test_func(self):
        user = self.request.user
        return user.is_staff or self.get_object().user == user

    def get_success_url(self):
        return reverse('authapp:users-details', kwargs={'pk': self.object.pk})

    def get_object(self):
        user = User.objects.get(pk=self.kwargs.get('pk'))
        return user.profile

class UsersListView(ListView):
    template_name = 'authapp/users_list.html'
    queryset = User.objects.filter(is_active=True)
    context_object_name = 'users'


class UserDetailsView(DetailView):
    template_name = 'authapp/users_details.html'
    model = User
    context_object_name = 'userr'


def set_cookies(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookies set! ')
    response.set_cookie('name', 'Jhon', max_age=3600)
    return response


def get_cookies(request: HttpRequest) -> HttpResponse:
    cookies = request.COOKIES.get('name', 'Cookies is empty!')
    response = HttpResponse(f'{cookies}')
    return response


def set_session(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Session set! ')
    request.session['name'] = 'Jhon'
    return response


def get_session(request: HttpRequest) -> HttpResponse:
    session = request.session.get('name', 'Session is empty!')
    response = HttpResponse(f'{session}')
    return response

mysite/authapp/templates/authapp/about_me.html
{% extends 'authapp/base.html' %}

{% block title %}
  About me
{% endblock %}


{% block body %}
  <h1>User info</h1>
  {% if user.is_authenticated %}
    <h2>Detail</h2>
    <p>Username: {{ user.username }}</p>
    <p>Avatar:
      {% if user.profile.avatar %}
        <img src="{{user.profile.avatar.url}}" alt="{{user.profile.avatar.name}}"/>
      {% else %}
        Нет Аватара
      {% endif %}
    </p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Bio: {{ user.profile.bio }}</p>

    <p><a href="{% url 'authapp:user-update' pk=user.pk %}">Изменить</a></p>
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
{% endblock %}

mysite/authapp/templates/authapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/authapp/templates/authapp/profile_update.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Изменение пользователя {{ object.username }}
{% endblock %}

{% block body %}
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <p><button type="submit">Изменить</button></p>
        </form>
    </div>
    <div>
        {% if user.pk != object.user.pk %}
            <p><a href="{% url 'authapp:users-details' pk=object.user.pk %}">Назад к профилю пользователя {{ object.user.username }}</a></p>
        {% else %}
            <p><a href="{% url 'authapp:about-me' %}">Назад к моему профилю {{ object.user.pk }}</a></p>
        {% endif %}
    </div>
{% endblock %}

mysite/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% block title %}
  Регистрация
{% endblock %}


{% block body %}
  <h1>Регистрация</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register" />
  </form>
{% endblock %}

mysite/authapp/templates/authapp/users_details.html
{% extends 'authapp/base.html' %}

{% block title %}
  User: {{userr.username}}
{% endblock %}


{% block body %}

  <h1>User info</h1>
  <h2>Detail</h2>
  <p>Username: {{ userr.username }}</p>
  <p>Avatar:
    {% if userr.profile.avatar %}
      <img src="{{userr.profile.avatar.url}}" alt="{{userr.profile.avatar.name}}"/>
    {% else %}
      Нет Аватара
    {% endif %}
  </p>
  <p>First name: {{ userr.first_name }}</p>
  <p>Last name: {{ userr.last_name }}</p>
  <p>Email: {{ userr.email }}</p>
  <p>Bio: {{ userr.profile.bio }}</p>

  {% if user.is_staff or user.pk == userr.pk %}
    <p><a href="{% url 'authapp:user-update' pk=userr.pk %}">Изменить</a></p>
  {% endif %}


{% endblock %}

mysite/authapp/templates/authapp/users_list.html
{% extends 'authapp/base.html' %}

{% block title %}
    Users
{% endblock %}

{% block body %}
    <div>
        {% if users %}
            {% for user in users %}
              <div>
                <p>{{ forloop.counter }} <a href="{% url 'authapp:users-details' pk=user.pk %}"> {% firstof user.first_name user.username %} </a> </p>
              </div>
            {% endfor %}
        {% else %}
            <p>Пользователей нет</p>
        {% endif %}
    </div>
{% endblock %}