mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from .sitemaps import sitemaps

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls'), name='shop'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

urlpatterns += [
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('request/', include('requestdataapp.urls'), name='request'),
    path('accounts/', include('authapp.urls'), name='auth'),
    path('blogs/', include('blogapp.urls'), name='blogs'),
    path('shop/', include('shopapp.urls'), name='shop'),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

mysite/shopapp/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import shop_index, ProductCreateView, ProductsListView, ProductDetailsView, \
    ProductUpdateView, ProductDeleteView, OrdersDetailsView, OrdersUpdateView, OrdersDeleteView, OrdersListView, \
    OrdersCreateView, OrdersDataExportView, ProductViewSet, OrderViewSet, LatestProductsFeed, UserOrdersListView, \
    UserOrdersExportView
    # UserOrderViewSet, UserOrdersExportView

app_name = 'shopapp'

routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)
# routers.register('user-orders1', UserOrderViewSet)


urlpatterns = [
    path('', shop_index, name='shop_index'),
    path('api/', include(routers.urls)),
    path('products-add/', ProductCreateView.as_view(), name='products-add'),
    path('products-list/', ProductsListView.as_view(), name='products-list'),
    path('products-details/<int:pk>/', ProductDetailsView.as_view(), name='products-details'),
    path('products-details/<int:pk>/update/', ProductUpdateView.as_view(), name='products-update'),
    path('products-details/<int:pk>/delete/', ProductDeleteView.as_view(), name='products-delete'),
    path('products/latest/feed/', LatestProductsFeed(), name='products-feed'),
    path('orders-add/', OrdersCreateView.as_view(), name='orders-add'),
    path('orders-list/', OrdersListView.as_view(), name='orders-list'),
    path('orders/export/', OrdersDataExportView.as_view(), name='orders-export'),
    path('orders-details/<int:pk>/', OrdersDetailsView.as_view(), name='orders-details'),
    path('orders-details/<int:pk>/update/', OrdersUpdateView.as_view(), name='orders-update'),
    path('orders-details/<int:pk>/delete/', OrdersDeleteView.as_view(), name='orders-delete'),
    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='user-orders'),
    path('users/<int:user_id>/orders/export/', UserOrdersExportView.as_view(), name='user-orders-export')
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from django.utils.translation import gettext_lazy as _


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    count = models.PositiveSmallIntegerField(default=0)
    changed = models.DateTimeField(auto_now=True)
    arhive = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user_product', null=True, default=None)

    class Meta:
        ordering = ['name', 'price']
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def __str__(self):
        return f'{self.pk}:  {self.name!r}'

    def get_absolute_url(self):
        return reverse('shopapp:products-details', kwargs={'pk': self.pk})

class Order(models.Model):
    address = models.TextField()
    comment = models.CharField(max_length=150)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user_orders', null=True, default=None)
    products = models.ManyToManyField(Product, related_name='orders', default=None)

    class Meta:
        ordering = False
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

mysite/shopapp/forms.py
from django import forms

from shopapp.models import Product, Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'description', 'price', 'discount', 'count'


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = 'address', 'comment', 'user', 'products'


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.syndication.views import Feed
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from django.core.cache import cache

from shopapp.models import Product, Order
from shopapp.serializes import ProductSerializer, OrderSerializer


class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        OrderingFilter,
    ]
    search_fields = [
        'name',
        'description',
    ]
    ordering_fields = [
        'pk',
        'name',
        'price',
        'discount',
        'count',
        'changed',
        'arhive',
        'created_by',
    ]


class UserOrdersExportView(PermissionRequiredMixin, View):
    permission_required = ['shopapp.view_order']

    def get(self, request, user_id) -> JsonResponse:
        cache_key = f'orders_usrid_{user_id}'
        orders = cache.get(cache_key)

        if orders is None:
            if not User.objects.filter(pk=user_id).exists():
                raise Http404

            orders = Order.objects.prefetch_related('products').select_related('user').all()
            cache.set(cache_key, list(orders), 60)

        serializer = OrderSerializer(orders, many=True)

        return JsonResponse({'orders': serializer.data})


# class UserOrderViewSet(ModelViewSet):
#     queryset = Order.objects.prefetch_related('products').select_related('user').all()
#     serializer_class = OrderSerializer
#     lookup_field = 'user_id'
#
#     @action(methods=['get'], detail=True)
#     def list_user_orders(self, request, user_id=None):
#         cache_key = f'orders_usrid_{user_id}'
#         queryset = cache.get(cache_key)
#
#         if queryset is None:
#             if not User.objects.filter(pk=user_id).exists():
#                 raise Http404
#
#             queryset = self.queryset.filter(user_id=user_id).order_by('pk')
#             cache.set(cache_key, list(queryset), 60)
#
#         serializer = self.get_serializer(queryset, many=True)
#
#         return Response(serializer.data)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.prefetch_related('products').select_related('user').all()
    serializer_class = OrderSerializer

    filter_backends = [
        DjangoFilterBackend,
        OrderingFilter,
    ]
    filterset_fields = [
        'address',
        'comment',
        'promocode',
        'created',
        'user',
        'products',

    ]
    ordering_fields = [
        'pk',
        'address',
        'created',
        'user',
        'products',
    ]

def shop_index(request: HttpRequest) -> HttpResponse:
    """
    Отображает страницу shop_index
    :param request: request
    :return: html - страница
    """

    return render(request, 'shopapp/shop_index.html', context={})


class ProductsListView(ListView):
    template_name = 'shopapp/products_list.html'
    queryset = Product.objects.filter(arhive=False)
    context_object_name = 'products'


class LatestProductsFeed(Feed):
    title = 'Products feed'
    descriptions = 'This is Products feed'
    link = reverse_lazy('shopapp:products-list')

    def items(self):
        return Product.objects.filter(arhive=False)[:5]

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:30]

    # def item_link(self, item: Product):
    #     return reverse('shopapp:products-details', kwargs={'pk': item.pk})


class ProductDetailsView(DetailView):
    template_name = 'shopapp/product_details.html'
    model = Product
    context_object_name = 'product'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = ['shopapp.add_product']
    model = Product
    fields = 'name', 'description', 'price', 'discount', 'count'
    template_name_suffix = '_add'
    success_url = reverse_lazy('shopapp:products-list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        response = super().form_valid(form)

        return response


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        user = self.request.user
        return user.has_perm('shopapp.change_product') and \
            self.get_object().created_by == user

    model = Product
    fields = 'name', 'description', 'price', 'discount', 'count'
    template_name_suffix = '_update'

    def get_success_url(self):
        return reverse('shopapp:products-details', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products-list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.arhive = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = 'shopapp/user_orders_list.html'
    context_object_name = 'orders'

    def get_queryset(self) -> QuerySet:
        user_id = self.kwargs['user_id']
        orders = Order.objects.select_related('user').prefetch_related('products').filter(user__pk=user_id)

        try:
            self.owner = orders[0].user
        except IndexError:
            try:
                self.owner = User.objects.get(pk=user_id)
            except User.DoesNotExist:
                raise Http404

        return orders

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner'] = self.owner

        return context


class OrdersListView(LoginRequiredMixin, ListView):
    template_name = 'shopapp/orders_list.html'
    queryset = Order.objects.select_related('user').prefetch_related('products')
    context_object_name = 'orders'


class OrdersDetailsView(DetailView):
    template_name = 'shopapp/order_details.html'
    queryset = Order.objects.select_related('user').prefetch_related('products')
    context_object_name = 'order'


class OrdersCreateView(CreateView):
    model = Order
    fields = 'address', 'comment', 'user', 'products'
    template_name_suffix = '_add'
    success_url = reverse_lazy('shopapp:orders-list')


class OrdersUpdateView(UpdateView):
    model = Order
    fields = 'address', 'comment', 'user', 'products'
    template_name_suffix = '_update'

    def get_success_url(self):
        return reverse('shopapp:orders-details', kwargs={'pk': self.object.pk})


class OrdersDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('shopapp:orders-list')


class OrdersDataExportView(PermissionRequiredMixin, View):
    permission_required = ['shopapp.view_order']

    def get(self, request) -> JsonResponse:
        orders = Order.objects.prefetch_related('products').order_by('pk').all()
        orders_data = [
            {
                'pk': order.pk,
                'address': order.address,
                'comment': order.comment,
                'promocode': order.promocode,
                'user': order.user_id,
                'products': [product.pk for product in order.products.all()],
            }
            for order in orders
        ]

        return JsonResponse({'orders': orders_data})

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/shopapp/templates/shopapp/order_add.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Добавление заказа
{% endblock %}

{% block body %}
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <p><button type="submit">Добавить</button></p>
        </form>
    </div>
    <div>
        <p><a href="{% url 'shopapp:shop_index' %}">Вернуться назад</a></p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order: {{order.pk}} delete
{% endblock %}

{% block body %}
    <div>
        <p> Вы точно хотите удалить?</p>
    </div>
    <div>
        <p><a href="{% url 'shopapp:orders-details' pk=object.pk %}">Вернуться назад</a></p>
    </div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <p><button type="submit">Удалить</button></p>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order: {{order.pk}}
{% endblock %}

{% block body %}
    <div>
        <p>Created: {{ order.created }} </p>
        <p>Address: {{ order.address }} </p>
        <p>Promocode: {% firstof order.promocode 'no promocode' %}</p>
        <p>Comment: {% firstof order.comment 'no comment' %}</p>
        <p>User: {{ order.user.username }}</p>
        <p>Products: </p>
            {% for product in order.products.all %}
                <p> {{ product.name }}: {{ product.price }}</p>
            {% endfor %}
    </div>
    <div>
        <p><a href="{% url 'shopapp:orders-list' %}">Вернуться назад</a></p>
        <p><a href="{% url 'shopapp:orders-update' pk=order.pk %}">Изменить</a></p>
        <p><a href="{% url 'shopapp:orders-delete' pk=order.pk %}">Удалить</a></p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Изменение заказа № {{ object.pk }}
{% endblock %}

{% block body %}
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <p><button type="submit">Изменить</button></p>
        </form>
    </div>
    <div>
        <p><a href="{% url 'shopapp:orders-details' pk=object.pk %}">Назад к заказу № {{ object.pk }}</a></p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink">Import CSV</a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/orders_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders
{% endblock %}

{% block body %}
    <div>
        {% if orders %}
            {% for order in orders %}
              <div>
                <p>Address: <a href="{% url 'shopapp:orders-details' pk=order.pk %}"> {{ order.address }} </a> </p>
                <p>Comment: {% firstof order.comment 'no comment' %}</p>
                <p>Promocode: {% firstof order.promocode 'no promocode' %}</p>
                <p>User: {{ order.user.username }}</p>
                <p>Products: </p>
                    {% for product in order.products.all %}
                        <p> {{ product.name }}: {{ product.price }}</p>
                    {% endfor %}
              </div>
            {% endfor %}
        {% else %}
            <p>Заказов нет</p>
        {% endif %}
    </div>
    <div>
        <p><a href="{% url 'shopapp:orders-add' %}">Добавить новый заказ</a></p>
        <p><a href="{% url 'shopapp:shop_index' %}">Вернуться назад</a></p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_add.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Добавление продукта
{% endblock %}

{% block body %}
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <p><button type="submit">Добавить</button></p>
        </form>
    </div>
    <div>
        <p><a href="{% url 'shopapp:shop_index' %}">Вернуться назад</a></p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product: {{product.pk}} - {{product.name}} delete
{% endblock %}

{% block body %}
    <div>
        <p> Вы точно хотите удалить?</p>
    </div>
    <div>
        <p><a href="{% url 'shopapp:products-details' pk=object.pk %}">Вернуться назад</a></p>
    </div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <p><button type="submit">Удалить</button></p>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product' %} : {{product.pk}} - {{product.name}}
{% endblock %}

{% block body %}
    <div>
        <p>{% translate 'Name' context 'product name' %}: {{product.name}} </p>
        {% translate 'no description' as no_description %}
        <p>{% translate 'Description' %}: {% firstof product.description no_description %}</p>
        <p>{% translate 'Price' %}: {{ product.price }}</p>
        {% translate 'no discount' as no_discount %}
        <p>{% translate 'Discount' %}: product.discount</p>
        <p>Count: {{ product.count }} unit</p>
        <p>Count: {{ product.count }} units</p>
        {% blocktranslate %}
        <p>Changed: {{ product.changed }}</p>
        <p>Archived: {{ product.arhive }}</p>
        {% endblocktranslate %}
    </div>
    <div>

        {% url 'shopapp:products-list' as prod_list_url%}
        {% url 'shopapp:products-delete' as prod_delete_url%}
        {% blocktranslate %}
        <p><a href="{{prod_list_url}}">Back</a></p>
        <p><a href="{{prod_delete_url}}">Archive</a></p>
        {% endblocktranslate %}
        {% if perms.shopapp.change_product and product.created_by == user or user.is_superuser %}
            <p><a href="{% url 'shopapp:products-update' pk=product.pk %}">{% translate 'To change' %}</a></p>
        {% endif %}

    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_update.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Изменение продукта № {{ object.pk }}
{% endblock %}

{% block body %}
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <p><button type="submit">Изменить</button></p>
        </form>
    </div>
    <div>
        <p><a href="{% url 'shopapp:products-details' pk=object.pk %}">Назад к продукту № {{ object.pk }}</a></p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products
{% endblock %}

{% block body %}
    <div><h1>Products</h1></div>
    <div>
        {% if products %}
            {% for product in products %}
              <div>
                <p>Name: <a href="{% url 'shopapp:products-details' pk=product.pk %}"> {{ product.name }} </a> </p>
                <p>Price: {{ product.price }}</p>
                <p>Discount: {% firstof product.discount 'no discount' %}</p>
              </div>
            {% endfor %}
        {% else %}
            <p>Продуктов нет</p>
        {% endif %}
    </div>
    <div>
        {% if perms.shopapp.add_product %}
            <p><a href="{% url 'shopapp:products-add' %}">Добавить новый продукт</a></p>
        {% endif %}
        <p><a href="{% url 'shopapp:shop_index' %}">Вернуться назад</a></p>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/shop_index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    {% load static %}
    <div>
        <ul>
            <p><a href="{% url 'shopapp:products-list' %}">Продукты</a></p>
            <p><a href="{% url 'shopapp:orders-list' %}">Заказы</a></p>
        </ul>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}

{% load cache %}

{% block title %}
    Orders
{% endblock %}

{% block body %}
    <div>
        {% if orders %}
            <h3> Пользователь {{owner.username}} выполнил следующие заказы </h3>
            {% cache 100 orders owner.pk %}
            {% for order in orders %}
              <div>
                <p>Address: <a href="{% url 'shopapp:orders-details' pk=order.pk %}"> {{ order.address }} </a> </p>
                <p>Comment: {% firstof order.comment 'no comment' %}</p>
                <p>Promocode: {% firstof order.promocode 'no promocode' %}</p>
                <p>User: {{ order.user.username }}</p>
                <p>Products: </p>
                    {% for product in order.products.all %}
                        <p> {{ product.name }}: {{ product.price }}</p>
                    {% endfor %}
              </div>
            {% endfor %}
            {% endcache %}
        {% else %}
            <p> У пользователя {{owner.username}} еще нет заказов </p>
        {% endif %}
    </div>
    <div>
        <p><a href="{% url 'shopapp:orders-add' %}">Добавить новый заказ</a></p>
        <p><a href="{% url 'shopapp:shop_index' %}">Вернуться назад</a></p>
    </div>
{% endblock %}